name: Update Cinema Schedule

on:
  schedule:
    - cron: '0 2 * * *' # Runs at 02:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # We tell pip to look inside the cinemacity folder
        run: |
          python -m pip install --upgrade pip
          pip install -r cinemacity/requirements.txt

      - name: Run Scraper
        # We tell python to run the script inside the cinemacity folder
        run: python cinemacity/scraper.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "CinemaBot"
          git config --global user.email "bot@noreply.github.com"
          # We stage the specific file in the subfolder
          git add cinemacity/index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update movie schedule [skip ci]" && git push)